---
# ironicbadger.docker_compose_generator
docker_compose_generator_output_path: "{{services_path}}/ansible"

# global vars
global_env_vars:
  - "PUID={{ docker_compose_generator_uid }}"
  - "PGID={{ docker_compose_generator_gid }}"
  - "UMASK={{ docker_compose_generator_umask }}"
  - "TZ={{ ntp_timezone }}"

containers:
###
  - service_name: portainer
    active: true
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{appdata_path}}/portainer_data:/data"
    restart: always
###
  - service_name: homer
    active: true
    image: "b4bz/homer:latest"
    container_name: "homer"
    environment:
      - "INIT_ASSETS=1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`homer.silentijsje.com`)"
      - "traefik.http.routers.homer.entrypoints=https"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    volumes:
      - "{{appdata_path}}/homer/site/:/www/assets"
    ports:
      - 8085:8080
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: syncthing
    active: true
    image: lscr.io/linuxserver/syncthing:latest
    hostname: syncthing
    include_global_env_vars: true
    volumes:
      - "{{appdata_path}}/syncthing:/config"
      - "/mnt/syncthing:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.silentijsje.com`)"
      - "traefik.http.routers.syncthing.entrypoints=https"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
###
  - service_name: traefik
    active: true
    image: traefik:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    include_global_env_vars: true
    environment:
      - "CF_DNS_API_TOKEN={{CF_DNS_API_TOKEN}}"
      - "TRAEFIK_DASHBOARD_CREDENTIALS={{TRAEFIK_DASHBOARD_CREDENTIALS}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{appdata_path}}/traefik/data/traefik.yml:/traefik.yml:ro"
      - "{{appdata_path}}/traefik/data/acme.json:/acme.json"
      - "{{appdata_path}}/traefik/configs/:/configs/:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.silentijsje.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users={{TRAEFIK_DASHBOARD_CREDENTIALS}}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.silentijsje.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=silentijsje.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.silentijsje.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"
###
  - service_name: authelia
    active: true
    image: authelia/authelia:latest
    volumes:
      - "{{appdata_path}}/authelia/config/:/config/"
    environment:
      - "AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET={{AUTHELIA_JWT_SECRET}}"
      - "AUTHELIA_STORAGE_ENCRYPTION_KEY={{AUTHELIA_ENCRYPTION_KEY}}"
      - "AUTHELIA_NOTIFIER_SMTP_USERNAME={{AUTHELIA_SMTP_USERNAME}}"
      - "AUTHELIA_NOTIFIER_SMTP_PASSWORD={{AUTHELIA_SMTP_PASSWORD}}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.authelia.rule=Host(`authelia.silentijsje.com`)"
      - "traefik.http.routers.authelia.tls.certresolver=cloudflare"
      - "traefik.http.routers.authelia.entrypoints=https"
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/authz/forward-auth?authelia_url=https://authelia.silentijsje.com'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: unless-stopped
###
  - service_name: redis
    active: true
    image: redis:alpine
    container_name: auth-redis
    volumes:
      - "{{appdata_path}}/authelia/redis:/data"
    expose:
      - 6379
    restart: unless-stopped
###
  - service_name: watchtower
    active: true
    image: containrrr/watchtower:latest
    environment:
      - "WATCHTOWER_SCHEDULE=0 0 4 * * *"
      # WATCHTOWER_RUN_ONCE: true
      - "WATCHTOWER_DEBUG=false"
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_INCLUDE_RESTARTING=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    include_global_env_vars: true
###
  - service_name: sabnzbd
    active: true
    image: lscr.io/linuxserver/sabnzbd:latest
    include_global_env_vars: true
    volumes:
      - "{{ appdata_path }}/sabnzbd:/config"
      - "{{ container_media_path }}:/data"
      - "{{ sabnzbd_incomplete_downloads_path }}:/incomplete" #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`sabnzbd.silentijsje.com`)"
      - "traefik.http.routers.homer.entrypoints=https"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    ports:
      - 8080:8080
    restart: unless-stopped
###
  - service_name: jellyseerr
    active: true
    image: fallenbagel/jellyseerr:latest
    include_global_env_vars: true
    volumes:
      - "{{ appdata_path }}/jellyseerr:/app/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`overseerr.silentijsje.com`)"
      - "traefik.http.routers.homer.entrypoints=https"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.services.homer.loadbalancer.server.port=5055"
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    ports:
      - 5055:5055
    restart: unless-stopped
###
  - service_name: prowlarr
    active: true
    image: "lscr.io/linuxserver/prowlarr:latest"
    container_name: "prowlarr"
    volumes:
      - "{{ appdata_path }}/prowlarr:/config"
      - "{{ container_media_path }}:/data"
    ports:
      - 9696:9696
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: radarr
    active: true
    image: "lscr.io/linuxserver/radarr:latest"
    container_name: "radarr"
    volumes:
      - "{{ appdata_path }}/radarr:/config"
      - "{{ container_media_path }}:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`radarr.silentijsje.com`)"
      - "traefik.http.routers.homer.entrypoints=https"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.services.homer.loadbalancer.server.port=7878"
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    ports:
      - 7878:7878
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: sonarr
    active: true
    image: "lscr.io/linuxserver/sonarr:latest"
    container_name: "sonarr"
    volumes:
      - "{{ appdata_path }}/sonarr:/config"
      - "{{ container_media_path }}:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`sonarr.silentijsje.com`)"
      - "traefik.http.routers.homer.entrypoints=https"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.services.homer.loadbalancer.server.port=8989"
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    ports:
      - 8989:8989
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: animarr
    active: true
    image: "lscr.io/linuxserver/sonarr:latest"
    container_name: "animarr"
    # network_mode: service:tailscale
    ports:
      - 8988:8989
    volumes:
      - "{{ appdata_path }}/animarr:/config"
      - "{{ container_media_path }}:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`animarr.silentijsje.com`)"
      - "traefik.http.routers.homer.entrypoints=https"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.services.homer.loadbalancer.server.port=8988"
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: bazarr
    active: true
    image: "lscr.io/linuxserver/bazarr:latest"
    container_name: "bazarr"
    volumes:
      - "{{ appdata_path }}/bazarr:/config"
      - "{{ container_media_path }}:/data"
    ports:
      - 6767:6767
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: pihole
    active: true
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    environment:
      - "WEBPASSWORD={{ pihole_web_password }}"
      - "PIHOLE_DNS_=9.9.9.9;1.1.1.1"
      - "DNSSEC=true"
      - "DNSMASQ_LISTENING=all"
    include_global_env_vars: true
    volumes:
      - "{{appdata_path}}/pihole/etc-pihole:/etc/pihole"
      - "{{appdata_path}}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped