---
# ironicbadger.docker_compose_generator
docker_compose_generator_output_path: "{{services_path}}"

# global vars
global_env_vars:
  - "PUID={{ docker_compose_generator_uid }}"
  - "PGID={{ docker_compose_generator_gid }}"
  - "UMASK={{ docker_compose_generator_umask }}"
  - "TZ={{ ntp_timezone }}"

containers:
###
  - service_name: portainer
    active: true
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{appdata_path}}/portainer_data:/data"
    restart: always
###
  - service_name: jellyfin
    image: jellyfin/jellyfin
    active: true
    include_global_env_vars: true
    volumes:
      - "{{appdata_path}}/jellyfin/config:/config"
      - "{{appdata_path}}/jellyfin/cache:/cache"
      - "{{ container_media_path }}:/data:ro"
      - "{{ appdata_path }}/jellyfin/transcode:/transcode"
    restart: 'unless-stopped'
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
###
  - service_name: plex
    image: lscr.io/linuxserver/plex:latest
    active: true
    include_global_env_vars: true
    network_mode: host
    environment:
      - "VERSION=docker"
      - "PLEX_CLAIM=claim-XuZiyfMfXPH_49ec_gaC"
    volumes:
      - "{{appdata_path}}/plex/config:/config"
      - "{{ container_media_path }}:/data:ro"
      - "{{ appdata_path }}/plex/transcode:/transcode"
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped