---
# ironicbadger.docker_compose_generator
appdata_path: /mnt/docker
container_media_path: /mnt/media
docker_compose_generator_output_path: "/mnt/ansible"
sabnzbd_incomplete_downloads_path: /mnt/storage/incomplete

# global vars
global_env_vars:
  - "PUID={{ docker_compose_generator_uid }}"
  - "PGID={{ docker_compose_generator_gid }}"
  - "UMASK={{ docker_compose_generator_umask }}"
  - "TZ={{ ntp_timezone }}"

containers:
  - service_name: sabnzbd
    active: true
    image: lscr.io/linuxserver/sabnzbd:latest
    include_global_env_vars: true
    volumes:
      - "{{ appdata_path }}/sabnzbd:/config"
      - "{{ container_media_path }}:/data"
      - "{{ sabnzbd_incomplete_downloads_path }}:/incomplete" #optional
    ports:
      - 8080:8080
    restart: unless-stopped
###
  - service_name: jellyseerr
    active: true
    image: fallenbagel/jellyseerr:latest
    include_global_env_vars: true
    volumes:
      - "{{ appdata_path }}/jellyseerr:/app/config"
    ports:
      - 5055:5055
    restart: unless-stopped
###
  - service_name: prowlarr
    active: true
    image: "lscr.io/linuxserver/prowlarr:latest"
    container_name: "prowlarr"
    volumes:
      - "{{ appdata_path }}/prowlarr:/config"
      - "{{ container_media_path }}:/data"
    ports:
      - 9696:9696
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: radarr
    active: true
    image: "lscr.io/linuxserver/radarr:latest"
    container_name: "radarr"
    volumes:
      - "{{ appdata_path }}/radarr:/config"
      - "{{ container_media_path }}:/data"
    ports:
      - 7878:7878
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: sonarr
    active: true
    image: "lscr.io/linuxserver/sonarr:latest"
    container_name: "sonarr"
    volumes:
      - "{{ appdata_path }}/sonarr:/config"
      - "{{ container_media_path }}:/data"
    ports:
      - 8989:8989
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: animarr
    active: true
    image: "lscr.io/linuxserver/sonarr:latest"
    container_name: "animarr"
    # network_mode: service:tailscale
    ports:
      - 8988:8989
    volumes:
      - "{{ appdata_path }}/animarr:/config"
      - "{{ container_media_path }}:/data"
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: bazarr
    active: true
    image: "lscr.io/linuxserver/bazarr:latest"
    container_name: "bazarr"
    volumes:
      - "{{ appdata_path }}/bazarr:/config"
      - "{{ container_media_path }}:/data"
    ports:
      - 6767:6767
    include_global_env_vars: true
    restart: unless-stopped
###
  - service_name: portainer_agent
    active: true
    image: portainer/agent:2.19.5
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
###
  - service_name: watchtower
    active: true
    image: containrrr/watchtower:latest
    environment:
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      # WATCHTOWER_RUN_ONCE: true
      WATCHTOWER_DEBUG: false
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_RESTARTING: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    include_global_env_vars: true  - service_name: traefik_local
    active: true
    image: traefik:v3.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    environment:
      CF_DNS_API_TOKEN: "{{CF_DNS_API_TOKEN}}"
      TRAEFIK_DASHBOARD_CREDENTIALS: "{{TRAEFIK_DASHBOARD_CREDENTIALS}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{appdata_path}}/traefik/data/traefik.yml:/traefik.yml:ro"
      - "{{appdata_path}}/traefik/data/acme.json:/acme.json"
      - "{{appdata_path}}/traefik/configs/:/configs/:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.silentijsje.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users={{TRAEFIK_DASHBOARD_CREDENTIALS}}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.local.silentijsje.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=local.silentijsje.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.silentijsje.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"
###
###
  - service_name: tailscale
    active: true
    image: tailscale/tailscale
    hostname: testing
    environment:
      - "TS_AUTHKEY={{ TAILSCALE_OAUTH_CONTAINER }}?ephemeral=false"
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - "{{ appdata_path }}//tailscale/state:/var/lib/tailscale"
      - "{{ appdata_path }}//tailscale/config:/config"
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped