---
# all non secret vars
zfs: {
  poolName: ssd,
  DISK1: '/dev/sdb',
  DISK2: '/dev/sdc',
}

usergroups:
  - family
  - admins

users:
  - {name: 'stanley', groups: 'family, admins', smbpasswd: 'stanley'}

adminuser: gamer0308 # should be an existing one from above

shared_folders:
  - {name: 'Images', path: '/{{zfs.poolName}}/media/images'}
  - {name: 'Music', path: '/{{zfs.poolName}}/media/music'}
  - {name: 'Shared folder', path: '/{{zfs.poolName}}/personal/all'}
  - {name: 'Shared Backup Folder', path: '/{{zfs.poolName}}/backup/all'}

shared_folders_group: family