---
# all non secret vars
users:
  - {name: "stanley", groups: "stanley, admins, family, docker, sudo", password: "$6$2fbOo.aG9Ij/H1IN$YgUHcEnKgsRNyO6KplOYD0OfRZExFcCllMWBvnq2Jp1HjVG8aFdJJSY/HL9jdiXLfCToLq4QN4jkSZ3WRM/PA."}

usergroups:
  - {name: "stanley", gid: 1000}
  - {name: "family", gid: 1001}
  - {name: "admins", gid: 1002}