---
- name: Mount ephemeral SMB volume
  ansible.posix.mount:
    src: //10.0.33.3/ssd_storage
    path: /mnt/ssd_storage
    opts: "rw,vers=3,file_mode=0600,dir_mode=0700,username={{ ad_username }},password={{ ad_password }}"
    fstype: cifs
    state: mounted