---
- name: Create CIFS credentials file
  copy:
    content:
      username={{CIFS_Username}}
      password={{CIFS_Password}}
    dest: "{{CIFS_credential_location}}"
    mode: '0600'

- name: Create shares folders
  file:
    path: "/mnt/{{ item.name }}"
    state: directory
    owner: "{{item.user}}"
    group: "{{item.group}}"
    mode: "0770"
  with_items:
    - "{{shares_mount}}"

- name: Mount ephemeral SMB volume
  ansible.posix.mount:
    src: //10.0.33.3/ssd_storage
    path: /mnt/ssd_storage
    opts: "rw,vers=3,file_mode=0600,dir_mode=0700,username={{ ad_username }},password={{ ad_password }}"
    fstype: cifs
    state: mounted

# - name: Mount network shares
#   ansible.posix.mount:
#     src: "//{{ item.ip }}/{{ item.name }}"
#     path: "/mnt/{{ item.name }}"
#     opts: "{{ smb_options }}"
#     fstype: "{{ item.type }}"
#     state: "{{ item.state }}"
#   with_items:
#     "{{ shares_mount }}"