---
- name: Create CIFS credentials file
  copy:
    content:
      username={{CIFS_Username}}
      password={{CIFS_Password}}
    dest: "{{CIFS_credential_location}}"
    mode: '0600'

- name: Create shares folders
  file:
    path: "/mnt/{{ item.name }}"
    state: directory
    owner: "{{item.user}}"
    group: "{{item.group}}"
    mode: "0770"
  with_items:
    - "{{shares_mount}}"

- name: Mount network shares
  mount:
    src: "//{{ item.ip }}/{{ item.name }}"
    path: "/mnt/{{ item.name }}"
    opts: "rw,file_mode=0770,dir_mode=0770,uid=1000,gid=1000,credentials={{CIFS_credential_location}}"
    fstype: cifs
    state: "{{ item.state }}"
  with_items:
    "{{ shares_mount }}"