---
- name: Create CIFS credentials file
  copy:
    content:
      username={{CIFS_Username}}
      password={{CIFS_Password}}
    dest: "{{CIFS_credential_location}}"
    mode: '0600'

- name: Mount proxmox ssd_storage volume
  mount:
    src: "//{{ item.ip }}/{{ item.name }}"
    path: "/mnt/{{ item.name }}"
    opts: "{{ smb_options }}"
    fstype: cifs
    state: "{{ item.state }}"
  with_items:
    "{{ shares_mount }}"