---
- name: pull containers and start them up and clean up old container files
  ansible.builtin.shell: "cd {{appdata_path}}/immich && docker compose pull && docker compose up -d && docker system prune --all -f"