http:
  #region routers 
  routers:
    proxmox:
      entryPoints:
        - https
      rule: Host(`proxmox.local.silentijsje.com`)
      middlewares:
        - default-headers
        - https-redirectscheme
        - local-ip-whitelist
      tls: {}
      service: proxmox

#region services
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: https://10.0.0.70:8006
        passHostHeader: true