http:
  routers:
    immich:
      rule: Host(`immich.silentijsje.com`)
      tls:
        certresolver:
          cloudflare
      service: immich
      entryPoints:
        - https
      middlewares:
        - default-headers
        - https-redirectscheme
        - cloudflare-whitelist
        - authelia

  services:
    immich:
      loadBalancer:
        servers:
          - url: http://10.0.0.80:2283