---
  - name: "Setting up the home server"
    hosts: storage
    
    # become root user, which is needed for most tasks
    become: yes
    become_user: root
    
    vars_files:
    - vars/vault.yml
    - vars/smb_vars.yml

    handlers:
    - name: restart smbd
      ansible.builtin.service:
        name: smbd
        state: restarted

    tasks:
    - name: Install generic needed packages
      apt:
        name:
        - software-properties-common
        - dkms
        state: latest
        cache_valid_time: 3600

    - import_tasks: storage-tasks/setupZFStask.yml
    - import_tasks: storage-tasks/setupUsersTask.yml
    - import_tasks: storage-tasks/setupSambaTask.yml