- hosts: bootstrap
  name: "bootstrap the servers"
  become: yes
  vars_files:
  - vars/vault.yml
  - vars/users.yml
  roles:
    - role: geerlingguy.docker
    - role: bootstrap

# - hosts: homeserver
#   name: "Setting up the home server"
#   become: yes
#   vars_files:
#   - vars/vault.yml
#   - vars/prod-media01.yml
#   - vars/users.yml
#   roles:
#     # - role: geerlingguy.docker
#     # - role: bootstrap
#     - role: IronicBadger.docker_compose_generator
#   tasks:
#   - import_tasks: tasks/update_os.yml
#   - import_tasks: tasks/traefik_acme.yml
#   - import_tasks: tasks/files.yml
#   - import_tasks: tasks/backup_scripts.yml
#   - import_tasks: tasks/docker_up.yml
#   - import_tasks: tasks/traefik_restart.yml
