# - hosts: bootstrap
#   name: "bootstrap the servers"
#   become: yes
#   vars_files:
#   - vars/vault.yml
#   - vars/users.yml
#   roles:
#     - role: bootstrap

- hosts: homeserver
  name: "Setting up the home server"
  become: yes
  vars_files:
  - vars/vault.yml
  - vars/prod-media01.yml
  - vars/users.yml
  roles:
    # - role: geerlingguy.docker
    # - role: bootstrap
    - role: IronicBadger.docker_compose_generator
  tasks:
  - import_tasks: tasks/update_os.yml
  - import_tasks: tasks/traefik_acme.yml
  - import_tasks: tasks/files.yml
  - import_tasks: tasks/backup_scripts.yml
  - import_tasks: tasks/docker_up.yml
  - import_tasks: tasks/traefik_restart.yml

# - hosts: streaming
#   name: "Setting up the streaming server"
#   become: yes
#   vars_files:
#   - vars/vault.yml
#   - vars/prod-video01.yml
#   - vars/users.yml
#   roles:
#     - role: bootstrap
#     - role: IronicBadger.docker_compose_generator
#   tasks:
#   - import_tasks: tasks/update_os.yml
#   - import_tasks: tasks/files.yml
#   - import_tasks: tasks/backup_scripts.yml
#   - import_tasks: tasks/docker_up.yml

- hosts: immich
  name: "Setting up the immich server"
  become: yes
  vars_files:
  - vars/vault.yml
  - vars/prod-immich01.yml
  - vars/users.yml
  # roles:
  #   - role: bootstrap
  tasks:
  - import_tasks: tasks/update_os.yml
  - import_tasks: tasks/files.yml
  - import_tasks: tasks/backup_scripts.yml
  - import_tasks: tasks/docker_immich_up.yml

# - hosts: "transcode"
#   name: "Setting up the transcode server"
#   become: yes
#   vars_files:
#   - vars/vault.yml
#   - vars/prod-transcode01.yml
#   - vars/users.yml
#   roles:
#     - role: bootstrap
#     - role: IronicBadger.docker_compose_generator
#   tasks:
#   - import_tasks: tasks/update_os.yml
#   - import_tasks: tasks/files.yml
#   - import_tasks: tasks/backup_scripts.yml
#   - import_tasks: tasks/docker_up.yml