- hosts: homeserver
  name: "Setting up the home server"
  become: yes
  vars_files:
  - vars/vault.yml
  - vars/homeserver.yml
  roles:
    # - role: bootstrap
    # - role: geerlingguy.docker
    - role: docker_copy
    - role: IronicBadger.docker_compose_generator
    - role: docker_run