# - hosts: 
#     - code02
#     - general-services
#     - external-services
#     - media-services
#     - storage
#   become: yes
#   vars_files:
#     - vars/vault.yml
#     - vars/smb_vars.yml
#   roles:
#     - role: bootstrap
#     - geerlingguy.docker

# - hosts: media-services
#   become: yes
#   vars_files:
#     - vars/vault.yml
#     - vars/general-services.yml
#   roles:
    # - role: docker_copy
    # - role: IronicBadger.docker_compose_generator
    #   tags: compose
    # - role: docker_run
#   tasks:
#   - import_tasks: storage-tasks/mountShares.yml

# - hosts: external-services
#   become: yes
#   vars_files:
#     - vars/vault.yml
#     - vars/general-services.yml
#   roles:
#     - role: docker_copy
#     - role: IronicBadger.docker_compose_generator
#       tags: compose
#     - role: docker_run
#   tasks:
#   - import_tasks: storage-tasks/mountShares.yml

- hosts: general-services
  become: yes
  vars_files:
    - vars/vault.yml
    - vars/general-services.yml
  roles:
    # - role: docker_copy
    # - role: IronicBadger.docker_compose_generator
    #   tags: compose
    # - role: docker_run
  tasks:
  - import_tasks: storage-tasks/mountSharesT.yml

# - hosts: storage
#   name: "Setting up the home server"
#   become: yes
#   become_user: root
#   vars_files:
#   - vars/vault.yml
#   - vars/smb_vars.yml
#   handlers:
#   - name: restart smbd
#     ansible.builtin.service:
#       name: smbd
#       state: restarted
#   tasks:
#   - name: Install generic needed packages
#     apt:
#       name:
#       - software-properties-common
#       - dkms
#       state: latest
#       cache_valid_time: 3600
#   - import_tasks: storage-tasks/setupZFStask.yml
#   - import_tasks: storage-tasks/setupUsersTask.yml
#   - import_tasks: storage-tasks/setupSambaTask.yml