# - hosts: 
#     - code02
#     - general-services
#     - external-services
#     - media-services
#   become: yes
#   vars_files:
#     - vars/vault.yml
#   roles:
#     - bootstrap
#     - geerlingguy.docker

- hosts: media-services
  become: yes
  vars_files:
    - vars/vault.yml
  roles:
    - role: docker_copy
    - role: IronicBadger.docker_compose_generator
      tags: compose
    - role: docker_run

# - hosts: external-services
#   become: yes
#   vars_files:
#     - vars/vault.yml
#   roles:
#     - role: docker_copy
#     - role: IronicBadger.docker_compose_generator
#       tags: compose
#     - role: docker_run
#     # - immich

# - hosts: general-services
#   become: yes
#   vars_files:
#     - vars/vault.yml
#   roles:
#     - role: docker_copy
#     - role: IronicBadger.docker_compose_generator
#       tags: compose
#     - role: docker_run