http:
  routers:
    radarr:
      rule: Host(`radarr.silentijsje.com`)
      tls:
        certresolver:
          cloudflare
      service: radarr
      entryPoints:
        - https
      middlewares:
        - default-headers
        - https-redirectscheme
        - cloudflare-whitelist
        - authelia

  services:
    radarr:
      loadBalancer:
        servers:
          - url: http://10.0.0.4:7878